### PR TITLE
Upgrade go dependencies

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup feature
/area dependency

#### What this PR does / why we need it:

With bazel removed in https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/333 / https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/336, we can more easily update go dependencies and the go.mod version declaration:

- go.mod: Update to go1.16
- go.mod: Update sigs.k8s.io/release-utils to v0.3.0
- go.mod: Upgrade all dependencies and `go mod tidy`

/assign @puerco @saschagrunert @cpanato 
cc: @kubernetes-sigs/release-engineering @listx @tylerferrara 

#### Special notes for your reviewer:

I expect the verify tests to fail, as the container it runs on is go1.15, which will cause go.sum diffs.
Will fix that in k/test-infra shortly.

#### Does this PR introduce a user-facing change?

```release-note
- go.mod: Update to go1.16
- go.mod: Update sigs.k8s.io/release-utils to v0.3.0
- go.mod: Upgrade all dependencies and `go mod tidy`
```

### CODE REVIEW

**Comment by justaugustus** [comment]
> I expect the verify tests to fail, as the container it runs on is go1.15, which will cause go.sum diffs.

ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_k8s-container-image-promoter/337/pull-cip-verify/1413027243239673856

> Will fix that in k/test-infra shortly.

https://github.com/kubernetes/test-infra/pull/22818

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Presuming this is a flake...
/test pull-cip-auditor-e2e

**Comment by justaugustus** [comment]
/override pull-cip-auditor-e2e
This is residual from https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/332 or https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/335.

@tylerferrara -- please take a look when you have a chance.

**Pull request merged**
