### PR TITLE
go: Init submodules for lib/ and pkg/

### PR DESCRIPTION
**Pull request by justaugustus**
Go submodule approach to solve https://github.com/kubernetes/release/pull/1619#discussion_r502631879.
Supersedes https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/260.

Now that we're attempting to integrate the manifest merging capabilities into k/release (https://github.com/kubernetes/release/pull/1619), we're running into the dreaded v2 semantic import versioning problem:

```console
require sigs.k8s.io/k8s-container-image-promoter: version "v2.4.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

ref: https://blog.golang.org/v2-go-modules, https://donatstudios.com/Go-v2-Modules, https://peter.bourgon.org/blog/2020/09/14/siv-is-unsound.html

This PR establishes go submodules for `lib/` and `pkg/` so that consumers can import libraries in this repo.

Following this merging, we'd tag minor versions (v0.1.0) of the new submodules:
- tag: `lib/v0.1.0`
- tag: `pkg/v0.1.0`

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

### CODE REVIEW

**Comment by justaugustus** [comment]
/kind feature
/assign @listx @dims 
cc: @kubernetes-sigs/release-engineering @bytecook

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
