### PR TITLE
.github: Add dependabot config

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup
/area dependency security release-eng

#### What this PR does / why we need it:

...because automated dependency updates are super cool!
/assign @puerco @saschagrunert @cpanato 
cc: @kubernetes-sigs/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
looks some go mod issue

**Comment by justaugustus** [comment]
> looks some go mod issue

Needs https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/337 now that https://github.com/kubernetes/test-infra/pull/22818 has merged.

**Comment by justaugustus** [comment]
Needs re-lgtm.

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by justaugustus** [comment]
This will fail the same way again.
/override pull-cip-auditor-e2e
ref: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/337#issuecomment-876218433

**Pull request merged**
