### PR TITLE
OWNERS: add ps882 as reviewer

### PR DESCRIPTION
**Pull request by ps882**

### CODE REVIEW

**Comment by listx** [comment]
For the record, @ps882 (Premdeep Sharma) is my teammate here at Google.

**Comment by listx** [comment]
Let's take care of all the red flags here first (need to join kubernetes-sigs org, etc) before merging this in.

**Comment by dims** [comment]
Hello @ps882 !

**Comment by ps882** [comment]
Greetings everyone !
cncf-cla is green now !

**Pull request merged**
