### PR TITLE
[WIP] Generate tarball archives for golden-tests

### PR DESCRIPTION
**Pull request by tylerferrara**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This change aims to save [tarball archives](https://docs.docker.com/engine/reference/commandline/save/) of every golden image within `//test-e2e/cip/golden` to later be integrated within [e2e.go](https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/master/test-e2e/cip/e2e.go). Images will contain the contents of a corresponding file defined in `//test-e2e/cip/golden/bar` and `//test-e2e/cip/golden/foo`. Each archive will copy the naming scheme of each file and be placed into `//test-e2e/cip/golden-archives`.

Additional information and goals of archive creation can be found in the [design doc](https://docs.google.com/document/d/1tQTb8dqKQtsL1a5jmCDbRg2MEDMkAnT07vrrxyZxLfk/edit?usp=sharing) corresponding with issue #300 

Partially satisfies #304 

#### Which issue(s) this PR fixes:
 

None

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

### CODE REVIEW

**Comment by justaugustus** [comment]
Needs rebase.
/unassign @dims @hoegaarden 
/assign @listx @justaugustus

**Comment by justaugustus** [comment]
(Rebased and pushed; I'm curious to see where the tests start failing after https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/291 was integrated...)

**Comment by tylerferrara** [comment]
Abandoned for #305 -> closing

**Pull request closed without merging**
