### PR TITLE
add bartsmykla to OWNERS

### PR DESCRIPTION
**Pull request by listx**
We need more people who are able to review changes, and Bart has been quite active recently.

/cc @dims @thockin

### CODE REVIEW

**Comment by listx** [comment]
@bartsmykla hey can you add yourself as a kubernetes-sigs member to fix the error at https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/174#issuecomment-584828029? Maybe @tpepper can help here?

**Comment by bartsmykla** [comment]
@listx done: https://github.com/kubernetes/org/pull/1644

**Pull request merged**
