### PR TITLE
Upgrade rules_docker so that it works with the latest bazel

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by listx** [comment]
Looks like the e2e test failed because it couldn't download the new rules?

```
WARNING: Download from https://github.com/bazelbuild/rules_pkg/releases/download/0.2.6/rules_pkg-0.2.6.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```

I can't get it either when I try to curl it. 🤷

**Comment by justinsb** [comment]
Thanks for checking @listx ... looks like this is because of https://github.com/bazelbuild/rules_pkg/issues/189  ... I'll fix!

**Comment by justinsb** [comment]
/retest

I'm wondering if the failure comes when I run tests concurrently...

**Comment by justinsb** [comment]
I'm guessing rules_tar or rules_docker changed the shas of the golden images

**Comment by listx** [comment]
@justinsb You are correct! Closing this in favor of #250. Can you LGTM there?

**Pull request closed without merging**
