### PR TITLE
Migrate `gh2gcs` tool/packages into repo

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

While working on the file promotion automation (https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/413) and chatting with @justinsb, I realized that `gh2gcs` is a promotion tool and should live alongside the rest for potential integrations (like exposing GitHub as a `filestore` for promotion).

- gh2gcs: Migrate from k/release@76deea6
- gh2gcs: Update import paths
- generated: Run `go mod tidy`

Signed-off-by: Stephen Augustus <foo@auggie.dev>

#### Does this PR introduce a user-facing change?

```release-note
Migrate `gh2gcs` tool/packages into repo
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Opened https://github.com/kubernetes-sigs/release-sdk/pull/3 to detangle the k/release imports.

**Comment by justaugustus** [comment]
Ready for review!
(Please note that this is a migration, not new code, so copyright dates should stay as-is and code formatting suggestions should be deferred to a follow-up PR.)

/assign @ameukam @puerco @Verolop @justinsb 
cc: @kubernetes-sigs/release-engineering

**Review by puerco — APPROVED** [review]
Thanks !!
/lgtm

**Comment by justaugustus** [comment]
Infra flake:
/test pull-cip-auditor-e2e

**Pull request merged**
