### PR TITLE
fix invalid url

### PR DESCRIPTION
**Pull request by wyyxd2017**
fix invalid url

### CODE REVIEW

**Comment by tpepper** [comment]
@wyyxd2017 if you need help figuring out a cla signing issue let us know and we can help

/ok-to-test

**Comment by listx** [comment]
@wyyxd2017 If you sign the CLA I will merge this. It is a legal thing that we have to abide by.

**Comment by justaugustus** [comment]
CLA has not been signed and this change will be superseded by active work in https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/291.
/close

**Pull request closed without merging**
