### PR TITLE
test-e2e: Use logrus instead of klog

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- Update k/release to https://github.com/kubernetes/release/tree/6313f69649456216fc6d08d74946f6c570fa0039
  (which drops the klog dependency: https://github.com/kubernetes/release/pull/1801)
- test-e2e: Use logrus instead of klog

#### Special notes for your reviewer:

/hold this is built on top of https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/282, so let's wait until that merges to rebase out commits.

#### Does this PR introduce a user-facing change?

```release-note
- Update k/release to https://github.com/kubernetes/release/tree/6313f69649456216fc6d08d74946f6c570fa0039
  (which drops the klog dependency: https://github.com/kubernetes/release/pull/1801)
- test-e2e: Use logrus instead of klog
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Flake:
/test pull-cip-auditor-e2e

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Rebased out https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/282.
/hold cancel

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
