### PR TITLE
Bazel updates

### PR DESCRIPTION
**Pull request by justaugustus**
(Part of https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/266.)

- bazel: Set .bazelversion to 2.2.0
- bazel: Set canonical reproducible form for bazel_rules_install
- bazel: Fixup gazelle rule generation
  
  We now have relative path replace directives in the repo to support
  submodules. Our current gazelle invocation will error on this.
  
  ref: bazelbuild/bazel-gazelle#650
- bazel: Update rules_go to v0.21.7 and gazelle to v0.22.2
- generated: Run make update

~(This includes content from https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/263, to make the rule updates less frustrating. I'll keep this on hold until that PR has merged and I have rebased this.)~

### CODE REVIEW

**Comment by listx** [comment]
Maybe try eliminating one commit at a time until the PR passes all tests?

**Comment by justaugustus** [comment]
/hold cancel
(this is looking good now)

/assign @listx @justinsb 
cc: @kubernetes-sigs/release-engineering

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
