### PR TITLE
Migrate kpromo/cip-mm tools/packages into repo

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup feature

#### What this PR does / why we need it:

Migrate kpromo/cip-mm tools/packages from k/release at 62b128c2
Unifying tooling in support of automated file promotion: https://github.com/kubernetes/k8s.io/issues/2624
Follow-up to https://github.com/kubernetes/release/pull/2232.

Signed-off-by: Stephen Augustus <foo@auggie.dev>

#### Does this PR introduce a user-facing change?

```release-note
Migrate kpromo/cip-mm tools/packages from k/release at 62b128c2
```

### CODE REVIEW

**Comment by justaugustus** [comment]
(There is a bit of link cleanup to do and some image building cleanup, so leaving this as WIP for the moment.)

**Comment by justaugustus** [comment]
> (There is a bit of link cleanup to do and some image building cleanup, so leaving this as WIP for the moment.)

Links are actually all good.
Since this is a large PR already, I'm going to opt to take the image building cleanup as a follow-up.

/assign @ameukam @puerco @saschagrunert @cpanato 
cc: @kubernetes-sigs/release-engineering

**Comment by puerco** [comment]
OK, I'm really rubber-stamping this as it is a repo migration but I already see some areas where we could SIG-Release-e-fy the code already.  
/lgtm

**Comment by justaugustus** [comment]
> OK, I'm really rubber-stamping this as it is a repo migration but I already see some areas where we could SIG-Release-e-fy the code already.
> /lgtm

Absolutely! I'm going to do some follow-up in a bit :)
...just didn't want the diff to be too crazy

**Pull request merged**
